version: "3.7"

services:
  postgres:
    image: postgres:16.1-alpine
    restart: always
    env_file:
      - ./apps/db/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
    driver: local
